const SEV_ORDER = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
const SEV_VN = { CRITICAL: 'Nghiêm trọng', HIGH: 'Cao', MEDIUM: 'Trung bình', LOW: 'Thấp', INFO: 'Thông tin' };
const SEV_COLOR_HEX = { CRITICAL: '#ff3366', HIGH: '#ff6b35', MEDIUM: '#fbbf24', LOW: '#38bdf8', INFO: '#6b7280' };
const SEV_DOCX_COLOR = { CRITICAL: 'FF4477', HIGH: 'FF8040', MEDIUM: 'FCD34D', LOW: '22D3EE', INFO: '94A3B8' };
const SEV_DOCX_BG = { CRITICAL: '3D0A18', HIGH: '3D1A08', MEDIUM: '3D3008', LOW: '08283D', INFO: '1E293B' };

window.SEV_ORDER = SEV_ORDER;
window.SEV_VN = SEV_VN;
window.SEV_COLOR_HEX = SEV_COLOR_HEX;
window.SEV_DOCX_COLOR = SEV_DOCX_COLOR;
window.SEV_DOCX_BG = SEV_DOCX_BG;
